/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_swdc_fx_deploy_system_impl_SystemProcessNative */

#ifndef _Included_org_swdc_fx_deploy_system_impl_SystemProcessNative
#define _Included_org_swdc_fx_deploy_system_impl_SystemProcessNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_fx_deploy_system_impl_SystemProcessNative
 * Method:    getProcessExecutablePath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_fx_deploy_system_impl_SystemProcessNative_getProcessExecutablePath
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
