/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_fx_deploy_system_impl_SystemSupportNative */

#ifndef _Included_org_swdc_fx_deploy_system_impl_SystemSupportNative
#define _Included_org_swdc_fx_deploy_system_impl_SystemSupportNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_fx_deploy_system_impl_SystemSupportNative
 * Method:    getProcessExecutablePath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_fx_deploy_system_impl_SystemSupportNative_getProcessExecutablePath
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
