/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_fx_deploy_system_impl_SystemSupportNative */

#ifndef _Included_org_swdc_fx_deploy_system_impl_SystemSupportNative
#define _Included_org_swdc_fx_deploy_system_impl_SystemSupportNative
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     org_swdc_fx_deploy_system_impl_SystemSupportNative
     * Method:    getRunningProcesses
     * Signature: ()Ljava/util/List;
     */
    JNIEXPORT jobject JNICALL Java_org_swdc_fx_deploy_system_impl_SystemSupportNative_getRunningProcesses
    (JNIEnv*, jclass);

    /*
     * Class:     org_swdc_fx_deploy_system_impl_SystemSupportNative
     * Method:    stopProcess
     * Signature: (J)Z
     */
    JNIEXPORT jboolean JNICALL Java_org_swdc_fx_deploy_system_impl_SystemSupportNative_stopProcess
    (JNIEnv*, jclass, jlong);

    /*
     * Class:     org_swdc_fx_deploy_system_impl_SystemSupportNative
     * Method:    getProcessExecutablePath
     * Signature: (J)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_org_swdc_fx_deploy_system_impl_SystemSupportNative_getProcessExecutablePath
    (JNIEnv*, jclass, jlong);

    /*
     * Class:     org_swdc_fx_deploy_system_impl_SystemSupportNative
     * Method:    installSystemModule
     * Signature: (J)Ljava/lang/Boolean;
     */
    JNIEXPORT jboolean JNICALL Java_org_swdc_fx_deploy_system_impl_SystemSupportNative_installSystemModule
    (JNIEnv*, jclass, jstring);

    /*
     * Class:     org_swdc_fx_deploy_system_impl_SystemSupportNative
     * Method:    uninstallSystemModule
     * Signature: (J)Ljava/lang/Boolean;
     */
    JNIEXPORT jboolean JNICALL Java_org_swdc_fx_deploy_system_impl_SystemSupportNative_uninstallSystemModule
    (JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
